{% set name = "pyhanko" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyHanko-{{ version }}.tar.gz
  sha256: 428c29a2071fecf3514deb064ac5238b86a8cb721eef2a7bd26cff0d7a319579

build:
  number: 0
  noarch: python
  entry_points:
    - pyhanko = pyhanko.__main__:launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
    - wheel
  run:
    - python >=3.7
    - asn1crypto >=1.4.0
    - click >=7.1.2
    - cryptography >=3.3.1
    - pyhanko-certvalidator ~=0.19.4
    - pytz >=2020.1
    - pyyaml >=5.3.1
    - qrcode >=6.1
    - requests >=2.24.0
    - tzlocal >=2.1

test:
  imports:
    - pyhanko
    - pyhanko.pdf_utils
  commands:
    - pip check
    - pyhanko --help
  requires:
    - pip

about:
  home: https://github.com/MatthiasValvekens/pyHanko
  summary: Tools for stamping and signing PDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
