{% set name = "pyhanko" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyHanko-{{ version }}.tar.gz
  sha256: b1f027f0f63a0c9f6c457652c8d1f5c959e6569ec79cdcdbee19cf8f9f2ad423

build:
  number: 1
  noarch: python
  entry_points:
    - pyhanko = pyhanko.__main__:launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - wheel
  run:
    - python >={{ python_min }}
    - asn1crypto >=1.4.0
    - click >=7.1.2
    - cryptography >=3.3.1
    - pyhanko-certvalidator ~=0.20.0
    - pytz >=2020.1
    - pyyaml >=5.3.1
    - qrcode >=6.1
    - requests >=2.24.0
    - tzlocal >=2.1

test:
  imports:
    - pyhanko
    - pyhanko.pdf_utils
  commands:
    - pip check
    - pyhanko --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MatthiasValvekens/pyHanko
  summary: Tools for stamping and signing PDF files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
